services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KRG\MessageBundle\Listener\MessageListener:
        tags: ['kernel.event_subscriber']

    KRG\MessageBundle\Service\Helper\:
        resource: '../../Service/Helper/*'

    KRG\MessageBundle\Service\Helper\Mailer:
        arguments:
            $from: '%krg_message_mailer_from%'
            $bcc: '%krg_message_mailer_bcc%'

    KRG\MessageBundle\Service\Registry\:
        resource: '../../Service/Registry/*'

    KRG\MessageBundle\Service\Factory\:
        resource: '../../Service/Factory/*'
        public: true

    KRG\MessageBundle\Service\Sender:
        abstract: true

    KRG\MessageBundle\Form\Type\:
        resource: '../../Form/Type/*'
        tags:
            - { name: 'form.type' }
